# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool install --global dotnet-warp'


- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'    
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    contents: DiscordDkpBot\appsettings.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    contents: DiscordDkpBot\AuthSettings.json.example.txt
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CmdLine@2
  inputs:
    script: dotnet-warp --output $(build.artifactStagingDirectory)\DiscordDkpBot.exe
    workingDirectory: DiscordDkpBot

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)' 
    archiveFile: '$(Build.ArtifactStagingDirectory)/$DiscordDkpBot-(Build.BuildId).zip' 