//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordDkpBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordDkpBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R0lGODlh5gF4AXAAACwAAAAA5gF4AYcAAAAKCxQOEwwNERUWDAkWDBIZFAsYFxccGiQcIRocJCUeKjQeOTMpGBMoGyYvJxcnJycsKDMrMissMjQ1KSYzKjc5NCg3Nzc3LUg/MmA9QRU7Qjk8QkQ1RlE6UUhPExNQGSRKLRdKNS1sERVwGCZuLhNtLCxFOkxHOmVvNENOShhSSTJdYB1aYzRtSxlsUTNsbRh4djVHR0dLSlNMUUtNU1RVSkdUS1RWU0pXV1dbTnZbYllcY2VqV0xhUHh4ckpoaGhra3JrcWptcXN0amhzbHR2c2t3d3ddT4NjUIJ5dIh+gRt9gTR8gUZ7gXx8g4N5mKWIFBqPGSqOLg+RJy6zFhu2GS2sMwuvJDOZG0OTLEW0GkKzKEONUxmJVimFeBWCezivRhSwTi2odDqJV0iIVmOGd0uJeG21Tk2vUmWpeFCwcmXFEB7CFzHDOhHCJDrGGULDLEXPThbSVizPYB/XYzDpWBbpWCjo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dkpkalmarea {
            get {
                return ResourceManager.GetString("dkpkalmarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4QAWRXhpZgAATU0AKgAAAAgAAAAAAAD//gA0T3B0aW1pemVkIGJ5IEpQRUdtaW5pIDMuMTQuMTQuNzI2NzA4NjAgMHhlNjVlYTY4MAD/2wBDAAgFBgcGBQgHBwcJCAgJDBQNDAsLDBgREg4UHBkeHRwZGxsfIy0mHyEqIhsbJzUnKi4wMjMyHiU3OzYxOy0xMjD/2wBDAQgJCQwKDBcNDRcwIBsgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDD/wAARCAEIAQgDASIAAhEBAxEB/8QAHAAAAQUBAQEAAAAAAAAAAAAABAACAwUGBwEI/8QAThAAAQMCBAQDBQQGBwQHCQAAAQIDEQAEBRIhMQYTQVEHImEUMnGBkSOhscEIFkJSYtEVJCUzkvDxF3Ki0jRDU3OCs+E4VFVjdISjsrT/xAAZAQADAQEBAAAAAAAAAAAAAAABAgMABAX/xAAjEQACAgIC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dkpmagg {
            get {
                return ResourceManager.GetString("dkpmagg", resourceCulture);
            }
        }
    }
}
