//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordDkpBotTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordDkpBotTests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;response&gt;
        ///  &lt;eqdkp&gt;
        ///    &lt;name&gt;Flames of Reverence&lt;/name&gt;
        ///    &lt;guild&gt;Flames of Reverence&lt;/guild&gt;
        ///    &lt;dkp_name&gt;DKP&lt;/dkp_name&gt;
        ///    &lt;version&gt;2.2.24.0&lt;/version&gt;
        ///    &lt;layout&gt;dicks&lt;/layout&gt;
        ///    &lt;base_layout&gt;normal&lt;/base_layout&gt;
        ///  &lt;/eqdkp&gt;
        ///  &lt;game&gt;
        ///    &lt;name&gt;eq&lt;/name&gt;
        ///    &lt;version&gt;2.3.2&lt;/version&gt;
        ///    &lt;language&gt;english&lt;/language&gt;
        ///    &lt;server_name/&gt;
        ///    &lt;server_loc/&gt;
        ///  &lt;/game&gt;
        ///  &lt;info&gt;
        ///    &lt;with_twink&gt;1&lt;/with_twink&gt;
        ///    &lt;date&gt;16.03.19 16:06:15&lt;/date&gt;
        ///    &lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EqDkpPlus_Points {
            get {
                return ResourceManager.GetString("EqDkpPlus_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;response&gt;
        ///  &lt;event&gt;
        ///    &lt;id&gt;1&lt;/id&gt;
        ///    &lt;name&gt;CLASSIC: Nagafen&apos;s Lair&lt;/name&gt;
        ///    &lt;value&gt;0.00&lt;/value&gt;
        ///    &lt;icon&gt;http://forguild.com/dkp//dkp/data/78337a0e75253a273091c0652415aa7b/files/event_icons/EQiconOld.ico&lt;/icon&gt;
        ///    &lt;multidkp_pools&gt;
        ///      &lt;multidkp_pool&gt;
        ///        &lt;id&gt;1&lt;/id&gt;
        ///        &lt;name&gt;FoR&lt;/name&gt;
        ///        &lt;desc&gt;base account&lt;/desc&gt;
        ///      &lt;/multidkp_pool&gt;
        ///    &lt;/multidkp_pools&gt;
        ///    &lt;itempools&gt;
        ///      &lt;itempool&gt;
        ///        &lt;id&gt;1&lt;/id&gt;
        ///        &lt;name&gt;default [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EventsXml {
            get {
                return ResourceManager.GetString("EventsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This XML file does not appear to have any style information associated with it. The document tree is shown below.
        ///&lt;response&gt;
        ///&lt;raid&gt;
        ///&lt;id&gt;2429&lt;/id&gt;
        ///&lt;date&gt;2019-04-02 02:45:48&lt;/date&gt;
        ///&lt;date_timestamp&gt;1554173148&lt;/date_timestamp&gt;
        ///&lt;note&gt;Compact&lt;/note&gt;
        ///&lt;event_id&gt;213&lt;/event_id&gt;
        ///&lt;event_name&gt;LDON: Takish-Hiz: Within the Compact&lt;/event_name&gt;
        ///&lt;added_by_id&gt;0&lt;/added_by_id&gt;
        ///&lt;added_by_name&gt;Fangor&lt;/added_by_name&gt;
        ///&lt;value&gt;15.00&lt;/value&gt;
        ///&lt;/raid&gt;
        ///&lt;raid&gt;
        ///&lt;id&gt;2428&lt;/id&gt;
        ///&lt;date&gt;2019-04-02 02:36:00&lt;/date&gt;
        ///&lt;date_timestamp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetRaids {
            get {
                return ResourceManager.GetString("GetRaids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;response&gt;
        ///  &lt;eqdkp&gt;
        ///    &lt;name&gt;Flames of Reverence&lt;/name&gt;
        ///    &lt;guild&gt;Flames of Reverence&lt;/guild&gt;
        ///    &lt;dkp_name&gt;DKP&lt;/dkp_name&gt;
        ///    &lt;version&gt;2.2.24.0&lt;/version&gt;
        ///    &lt;layout&gt;dicks&lt;/layout&gt;
        ///    &lt;base_layout&gt;normal&lt;/base_layout&gt;
        ///  &lt;/eqdkp&gt;
        ///  &lt;game&gt;
        ///    &lt;name&gt;eq&lt;/name&gt;
        ///    &lt;version&gt;2.3.2&lt;/version&gt;
        ///    &lt;language&gt;english&lt;/language&gt;
        ///    &lt;server_name/&gt;
        ///    &lt;server_loc/&gt;
        ///  &lt;/game&gt;
        ///  &lt;info&gt;
        ///    &lt;with_twink&gt;1&lt;/with_twink&gt;
        ///    &lt;date&gt;16.03.19 21:17:42&lt;/date&gt;
        ///    &lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaggDkp {
            get {
                return ResourceManager.GetString("MaggDkp", resourceCulture);
            }
        }
    }
}
