//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscordDkpBotTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscordDkpBotTests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;response&gt;
        ///  &lt;eqdkp&gt;
        ///    &lt;name&gt;Flames of Reverence&lt;/name&gt;
        ///    &lt;guild&gt;Flames of Reverence&lt;/guild&gt;
        ///    &lt;dkp_name&gt;DKP&lt;/dkp_name&gt;
        ///    &lt;version&gt;2.2.24.0&lt;/version&gt;
        ///    &lt;layout&gt;dicks&lt;/layout&gt;
        ///    &lt;base_layout&gt;normal&lt;/base_layout&gt;
        ///  &lt;/eqdkp&gt;
        ///  &lt;game&gt;
        ///    &lt;name&gt;eq&lt;/name&gt;
        ///    &lt;version&gt;2.3.2&lt;/version&gt;
        ///    &lt;language&gt;english&lt;/language&gt;
        ///    &lt;server_name/&gt;
        ///    &lt;server_loc/&gt;
        ///  &lt;/game&gt;
        ///  &lt;info&gt;
        ///    &lt;with_twink&gt;1&lt;/with_twink&gt;
        ///    &lt;date&gt;16.03.19 16:06:15&lt;/date&gt;
        ///    &lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EqDkp_Points {
            get {
                return ResourceManager.GetString("EqDkp_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;response&gt;
        ///  &lt;eqdkp&gt;
        ///    &lt;name&gt;Flames of Reverence&lt;/name&gt;
        ///    &lt;guild&gt;Flames of Reverence&lt;/guild&gt;
        ///    &lt;dkp_name&gt;DKP&lt;/dkp_name&gt;
        ///    &lt;version&gt;2.2.24.0&lt;/version&gt;
        ///    &lt;layout&gt;dicks&lt;/layout&gt;
        ///    &lt;base_layout&gt;normal&lt;/base_layout&gt;
        ///  &lt;/eqdkp&gt;
        ///  &lt;game&gt;
        ///    &lt;name&gt;eq&lt;/name&gt;
        ///    &lt;version&gt;2.3.2&lt;/version&gt;
        ///    &lt;language&gt;english&lt;/language&gt;
        ///    &lt;server_name/&gt;
        ///    &lt;server_loc/&gt;
        ///  &lt;/game&gt;
        ///  &lt;info&gt;
        ///    &lt;with_twink&gt;1&lt;/with_twink&gt;
        ///    &lt;date&gt;16.03.19 21:17:42&lt;/date&gt;
        ///    &lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaggDkp {
            get {
                return ResourceManager.GetString("MaggDkp", resourceCulture);
            }
        }
    }
}
